### ISSUE TITLE
FAILURE: Build failed with an exception after running react-native run-android

### ISSUE THREAD

**Issue by rajendraarora16** [INSITEQUIZ/INSITEQUIZ#5]
After running `react-native run-android` command, I have the following errors below:

```
PS G:\github_clones\INSITEQUIZ> react-native run-android
Scanning folders for symlinks in G:\github_clones\INSITEQUIZ\node_modules (32ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 42.034 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
PS G:\github_clones\INSITEQUIZ>
```

**Comment by rajendraarora16** [comment]
I faced this issue in windows, for mac you can refer [this](https://stackoverflow.com/questions/32634352/react-native-android-build-failed-sdk-location-not-found).

On windows, create a `local.properties` file in android directory and write sdk path:

`sdk.dir = C://Users//Rajendra arora//AppData//Local//Android//Sdk`

save and try running the command `react-native run-android` again.

Hope it helps!
