### ISSUE TITLE
Error: spawn cmd.exe ENOENT while running react-native run-android

### ISSUE THREAD

**Issue by rajendraarora16** [INSITEQUIZ/INSITEQUIZ#6]
I am getting the following error in windows while running command `react-native run-android`:

```
PS G:\github_clones\INSITEQUIZ> react-native run-android
Scanning folders for symlinks in G:\github_clones\INSITEQUIZ\node_modules (23ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportSupportV42301Library
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:prepareComFacebookFrescoDrawee130Library
:app:prepareComFacebookFrescoFbcore130Library
:app:prepareComFacebookFrescoFresco130Library
:app:prepareComFacebookFrescoImagepipeline130Library
:app:prepareComFacebookFrescoImagepipelineBase130Library
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library
:app:prepareComFacebookReactReactNative0552Library
:app:prepareComFacebookSoloaderSoloader010Library
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
:app:mergeDebugJniLibFolders
:app:transformNative_libsWithMergeJniLibsForDebug
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:installDebug
Installing APK 'app-debug.apk' on 'andy_man(AVD) - 7.1' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 1 mins 26.766 secs
Running adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (adb -s emulator-5554 shell am start -n com.insitequiz/com.insitequiz.MainActivity)...
Starting: Intent { cmp=com.insitequiz/.MainActivity }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
PS G:\github_clones\INSITEQUIZ>
```

**Comment by rajendraarora16** [comment]
It's a port issue, in my case I tried running below command on windows:

`npm run start PORT=8081`

and then `react-native run-android` command gave me the successful response.

Hope it helps!

**Comment by bluesuiter** [comment]
@rajendraarora16  thank you :)

**Comment by xhmrnz** [comment]
> It's a port issue, in my case I tried running below command on windows:
> 
> `npm run start PORT=8081`
> 
> and then `react-native run-android` command gave me the successful response.
> 
> Hope it helps!

Thanks sir, it works
